M48
; DRILL file {KiCad 7.0.5} date Sat Jun  3 16:26:33 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-03T16:26:33+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.000
%
G90
G05
T1
X20.32Y-22.86
X20.32Y-48.26
X101.6Y-22.86
X101.6Y-48.26
T2
X53.26Y-45.68
X58.42Y-33.02
T0
M30
